### ISSUE TITLE
RDFLIB: Exception when parsing the get response of a container

### ISSUE THREAD

**Issue by cdawei** [anusii/rdflib#41]
rdflib (version 0.2.8) throws an exception when parsing the get response of a directory with two resources:
- `ind-keys.ttl`
- `enc-keys.ttl`

Here's the exception
```bash
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'String'
#0      Graph._saveToGroups (package:rdflib/src/graph.dart:614:7)
#1      Graph.parseTurtle (package:rdflib/src/graph.dart:584:7)
```

And here's the response turtle string I want to parse
```
@prefix dc: <http://purl.org/dc/terms/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix posix: <http://www.w3.org/ns/posix/stat#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

<> <urn:npm:solid:community-server:meta:contentTypeParameter> _:b22466_b12514_b12510_n3-564;
    a ldp:Container, ldp:BasicContainer, ldp:Resource;
    dc:modified "2024-07-10T00:36:05.000Z"^^xsd:dateTime.
_:b22466_b12514_b12510_n3-564 <http://www.w3.org/2000/01/rdf-schema#label> "charset";
    <urn:npm:solid:community-server:meta:value> "utf-8".
<ind-keys.ttl> a ldp:Resource, <http://www.w3.org/ns/iana/media-types/text/turtle#Resource>;
    dc:modified "2024-07-10T04:54:04.000Z"^^xsd:dateTime.
<enc-keys.ttl> a ldp:Resource, <http://www.w3.org/ns/iana/media-types/text/turtle#Resource>;
    dc:modified "2024-06-27T12:01:32.000Z"^^xsd:dateTime.
<> posix:mtime 1720571765;
    ldp:contains <ind-keys.ttl>, <enc-keys.ttl>.
<ind-keys.ttl> posix:mtime 1720587244;
    posix:size 941.
<enc-keys.ttl> posix:mtime 1719489692;
    posix:size 2703.
```

**Comment by cdawei** [comment]
Could you please have a look @zheyxu ?

**Comment by cdawei** [comment]
Here's the triples from the python rdflib parser:
```
subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/ldp#Container

subject:  n69efd3c34ab047b98b7ba26493ea2659b1
predicate:  http://www.w3.org/2000/01/rdf-schema#label
object:  charset

subject:  file:///home/test/ind-keys.ttl
predicate:  http://www.w3.org/ns/posix/stat#mtime
object:  1720587244

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/ns/ldp#contains
object:  file:///home/test/enc-keys.ttl

subject:  file:///home/test/ind-keys.ttl
predicate:  http://www.w3.org/ns/posix/stat#size
object:  941

subject:  file:///home/test/enc-keys.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/iana/media-types/text/turtle#Resource

subject:  file:///home/test/enc-keys.ttl
predicate:  http://www.w3.org/ns/posix/stat#size
object:  2703

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://purl.org/dc/terms/modified
object:  2024-07-10T00:36:05+00:00

subject:  file:///home/test/enc-keys.ttl
predicate:  http://www.w3.org/ns/posix/stat#mtime
object:  1719489692

subject:  file:///home/test/ind-keys.ttl
predicate:  http://purl.org/dc/terms/modified
object:  2024-07-10T04:54:04+00:00

subject:  file:///home/test/enc-keys.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/ldp#Resource

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/ldp#Resource

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/ns/posix/stat#mtime
object:  1720571765

subject:  n69efd3c34ab047b98b7ba26493ea2659b1
predicate:  urn:npm:solid:community-server:meta:value
object:  utf-8

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/ns/ldp#contains
object:  file:///home/test/ind-keys.ttl

subject:  file:///home/test/enc-keys.ttl
predicate:  http://purl.org/dc/terms/modified
object:  2024-06-27T12:01:32+00:00

subject:  file:///home/test/get_dir_response.ttl
predicate:  urn:npm:solid:community-server:meta:contentTypeParameter
object:  n69efd3c34ab047b98b7ba26493ea2659b1

subject:  file:///home/test/ind-keys.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/iana/media-types/text/turtle#Resource

subject:  file:///home/test/get_dir_response.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/ldp#BasicContainer

subject:  file:///home/test/ind-keys.ttl
predicate:  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
object:  http://www.w3.org/ns/ldp#Resource
```

**Comment by cdawei** [comment]
And then call `graph.serialize(OUTPUT_FILE)` gives:
```
@prefix dc1: <http://purl.org/dc/terms/> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix ns1: <urn:npm:solid:community-server:meta:> .
@prefix posix: <http://www.w3.org/ns/posix/stat#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<file:///home/test/get_dir_response.ttl> a ldp:BasicContainer,
        ldp:Container,
        ldp:Resource ;
    dc1:modified "2024-07-10T00:36:05+00:00"^^xsd:dateTime ;
    ldp:contains <file:///home/test/enc-keys.ttl>,
        <file:///home/test/ind-keys.ttl> ;
    posix:mtime 1720571765 ;
    ns1:contentTypeParameter [ rdfs:label "charset" ;
            ns1:value "utf-8" ] .

<file:///home/test/enc-keys.ttl> a <http://www.w3.org/ns/iana/media-types/text/turtle#Resource>,
        ldp:Resource ;
    dc1:modified "2024-06-27T12:01:32+00:00"^^xsd:dateTime ;
    posix:mtime 1719489692 ;
    posix:size 2703 .

<file:///home/test/ind-keys.ttl> a <http://www.w3.org/ns/iana/media-types/text/turtle#Resource>,
        ldp:Resource ;
    dc1:modified "2024-07-10T04:54:04+00:00"^^xsd:dateTime ;
    posix:mtime 1720587244 ;
    posix:size 941 .
```

**Comment by zheyxu** [comment]
Hi @gjwgit @cdawei after some updates, treat BNode(_:b22466_b12514_b12510_n3-564) as blank node. get 

-------Serialized String--------
```
@prefix dc: <http://purl.org/dc/terms/> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix posix: <http://www.w3.org/ns/posix/stat#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<>
    <urn:npm:solid:community-server:meta:contentTypeParameter> BNode(_:b22466_b12514_b12510_n3-564) ;
    a ldp:Container, ldp:BasicContainer, ldp:Resource ;
    dc:modified "2024-07-10T00:36:05.000Z"^^xsd:dateTime ;
    posix:mtime "1720571765"^^xsd:int ;
    ldp:contains <ind-keys.ttl>, <enc-keys.ttl> .
BNode(_:b22466_b12514_b12510_n3-564)
    <http://www.w3.org/2000/01/rdf-schema#label> "charset"^^xsd:string ;
    <urn:npm:solid:community-server:meta:value> "utf-8"^^xsd:string .
<ind-keys.ttl>
    a ldp:Resource, <http://www.w3.org/ns/iana/media-types/text/turtle#Resource> ;
    dc:modified "2024-07-10T04:54:04.000Z"^^xsd:dateTime ;
    posix:mtime "1720587244"^^xsd:int ;
    posix:size "941"^^xsd:int .
<enc-keys.ttl>
    a ldp:Resource, <http://www.w3.org/ns/iana/media-types/text/turtle#Resource> ;
    dc:modified "2024-06-27T12:01:32.000Z"^^xsd:dateTime ;
    posix:mtime "1719489692"^^xsd:int ;
    posix:size "2703"^^xsd:int .
```
--------All triples in the graph-------
```
Triple<sub: , pre: urn:npm:solid:community-server:meta:contentTypeParameter, obj: BNode(_:b22466_b12514_b12510_n3-564)>
Triple<sub: , pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/ldp#Container)>
Triple<sub: , pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/ldp#BasicContainer)>
Triple<sub: , pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/ldp#Resource)>
Triple<sub: , pre: http://purl.org/dc/terms/modified, obj: Literal(2024-07-10T00:36:05.000Z, datatype: URIRef(http://www.w3.org/2001/XMLSchema#dateTime))>
Triple<sub: _:b22466_b12514_b12510_n3-564, pre: http://www.w3.org/2000/01/rdf-schema#label, obj: Literal(charset, datatype: URIRef(http://www.w3.org/2001/XMLSchema#string))>
Triple<sub: _:b22466_b12514_b12510_n3-564, pre: urn:npm:solid:community-server:meta:value, obj: Literal(utf-8, datatype: URIRef(http://www.w3.org/2001/XMLSchema#string))>
Triple<sub: ind-keys.ttl, pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/ldp#Resource)>
Triple<sub: ind-keys.ttl, pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/iana/media-types/text/turtle#Resource)>
Triple<sub: ind-keys.ttl, pre: http://purl.org/dc/terms/modified, obj: Literal(2024-07-10T04:54:04.000Z, datatype: URIRef(http://www.w3.org/2001/XMLSchema#dateTime))>
Triple<sub: enc-keys.ttl, pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/ldp#Resource)>
Triple<sub: enc-keys.ttl, pre: http://www.w3.org/1999/02/22-rdf-syntax-ns#type, obj: URIRef(http://www.w3.org/ns/iana/media-types/text/turtle#Resource)>
Triple<sub: enc-keys.ttl, pre: http://purl.org/dc/terms/modified, obj: Literal(2024-06-27T12:01:32.000Z, datatype: URIRef(http://www.w3.org/2001/XMLSchema#dateTime))>
Triple<sub: , pre: http://www.w3.org/ns/posix/stat#mtime, obj: Literal(1720571765, datatype: URIRef(http://www.w3.org/2001/XMLSchema#int))>
Triple<sub: , pre: http://www.w3.org/ns/ldp#contains, obj: URIRef(ind-keys.ttl)>
Triple<sub: , pre: http://www.w3.org/ns/ldp#contains, obj: URIRef(enc-keys.ttl)>
Triple<sub: ind-keys.ttl, pre: http://www.w3.org/ns/posix/stat#mtime, obj: Literal(1720587244, datatype: URIRef(http://www.w3.org/2001/XMLSchema#int))>
Triple<sub: ind-keys.ttl, pre: http://www.w3.org/ns/posix/stat#size, obj: Literal(941, datatype: URIRef(http://www.w3.org/2001/XMLSchema#int))>
Triple<sub: enc-keys.ttl, pre: http://www.w3.org/ns/posix/stat#mtime, obj: Literal(1719489692, datatype: URIRef(http://www.w3.org/2001/XMLSchema#int))>
Triple<sub: enc-keys.ttl, pre: http://www.w3.org/ns/posix/stat#size, obj: Literal(2703, datatype: URIRef(http://www.w3.org/2001/XMLSchema#int))>
```

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/rdflib/pull/42
